### ISSUE TITLE
consider changing startup scene to not include cube

### ISSUE THREAD

**Issue by hannesdelbeke** [Quackarooni/Default_Cube_Deletify#1]
consider changing startup scene to not include cube
https://docs.blender.org/manual/en/latest/interface/window_system/topbar.html#startup-file

**Comment by Quackarooni** [comment]
Yeah, I appreciate the comment, though this repo was intended to purely just be a joke addon I shared between friends. 
This wasn't meant to be practically useful, as there are far better ways to get rid of the default cube like you've pointed out.

**Comment by hannesdelbeke** [comment]
Ah you got me 😭🤣
